### ISSUE TITLE
Actividad 5

### ISSUE THREAD

**Issue by PedroGarcia11439** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-PedroGarcia11439#1]
Actividad 5
Cuadro comparativo
1BS
[Uploading Tipos de textos.pdf…]()

**Comment by PedroGarcia11439** [comment]
Este es el verdadero trabajo
Cuadro Comparativo
1BS
[Tipos de textos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-PedroGarcia11439/files/9649358/Tipos.de.textos.pdf)

**Comment by josealfredo79** [comment]
Calificacion  18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
